### PR TITLE
Add A4 & A5 & A6

### PR DESCRIPTION
**Pull request by bllin001**

### CODE REVIEW

**Comment by bllin001** [comment]
Hi Dr. Nelson, show me up about the conflict but I do not have this file in my repo

image

**Comment by bllin001** [comment]
Hi, Dr. Nelson.

The conflict can affect the PR?

Because I tried to do it one by one but I am still having same issue

**Comment by bllin001** [comment]
I do not what else I need to do

**Comment by phonedude** [comment]
I see the conflicting file as:

Conflicting files
assignments/.DS_Store

*please* stop issuing PRs for files outside of "assignments/Llinas-Marimon/" -- that's the only area that is for you.

**Comment by phonedude** [comment]
I was able to delete the .DS_store file and reopen.

**Pull request merged**
